### ISSUE TITLE
Tracker for changes addressed by mapping guide review

### ISSUE THREAD

**Issue by pipliggins** [globaldothealth/isaric#146]
- [x] Remove `country_iso3` (country of study site) from subject
- [x] Change `admission_date` to `earliest_admission_date` (use combinedType `min`)
   - [x] allow the required field to be either enrolment_date or earliest_admission_date
~Create issue for `sex_at_birth` - some studies have just 'sex' rather than sex at birth and include fields e.g. non-binary, transgender. What's the best way of dealing with this from a clinical data POV?~ Most of the 'non-binary' entries were mistranslations from Not Known. Places where 'trans' etc are present in the data dict do not have those values present in the data. A separate pull request #151 has been made for this.
- [x] change `pregnancy_gestational_outcome_weeks` to `pregnancy_gestational_age_weeks`
- [x] Convert `has_immunosuppression_therapy_treatment` to `has_immunosuppression`, inferred from either direct data or someone taking immunosuppressants. Taking immunosuppressants would then be recorded as a pre-admission med in future.
- [x] create general type out of `treatment_cardiovascular`
~add delirium to observations~ - Delirium is only recorded once so far, in conjunction with delirium, so passed on this for now.
- [x] change pneumonia observation to indicate all types, with context for viral, bacteria, on oxygen
- [x] use mmHg as default unit for paO2, pCO2
- [x] drop `time_of_admission`
- [x] move `transferred_from_another_facility` into visit
- [x] make guide a ReStructured text doc to include links.
- [x] Remove renal_replacement_therapy_dialysis from observations - this is a treatment covered by treatment_dialysis
- [x] Remove treatment_oxygen_mechanical_support - This is covered by invasive_ventilation. Originally mapped for SouthAfrica's MechanicalSupport field, which actually indicates _cardiovascular_ support (true for either ecmo or an intra-aortic balloon pump, can only be selected is CardiovascularSupport is True) not oxygen therapy.
- [x] Add 'bleeding' observation for when bleeding is not labelled as 'haemorrhage'.

**Comment by ekamau** [comment]
I like this .. and I think very useful.
